FROM python:3.9
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY config /code/config
COPY controller /code/controller
COPY models /code/models
COPY schemas /code/schemas
COPY services /code/services
COPY test  /code/test
COPY .env.production  /code/.env
copy main.py  /code/main.py
copy server.py /code/server.py

EXPOSE 8080
# CMD ["python", "server.py]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]